version: "3.8"

services:
  app:
    build: .
    ports:
      - 3000
    environment:
      AUTH0_AUDIENCE: ZiG0fuIV7rhOvYedlOXAL5wwl6FyLHid
      AUTH0_ISSUER: https://dev-baqlbrdt.us.auth0.com/
      JWKS_URL: https://dev-baqlbrdt.us.auth0.com/.well-known/jwks.json
      MONGODB_URL: mongodb://monbodb/dev?retryWrites=true&w=majority
      PORT: 3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo

  browser_tests:
    build:
      context: .
      # dockerfile: Dockerfile.browser_tests
    platform: "linux/amd64"
    depends_on:
      - app
    environment:
      START_URL: http://app:3000/
      # TAIKO_USERNAME: zuuttestuser@gmail.com
      # TAIKO_PASSWORD: ZUUTtester123!
      CYPRESS_auth_username: zuuttestuser@gmail.com
      CYPRESS_auth_password: ZUUTtester123!
      CYPRESS_auth_audience: https://dev-baqlbrdt.us.auth0.com/api/v2/
      CYPRESS_auth_url: https://dev-baqlbrdt.us.auth0.com/oauth/token
      CYPRESS_auth_client_id: ZiG0fuIV7rhOvYedlOXAL5wwl6FyLHid
      JWKS_URL: https://dev-baqlbrdt.us.auth0.com/.well-known/jwks.json
