import { ItemRecord } from '../../../src/airtable/ItemRecord';

const airtableTents: ItemRecord[] = [
  {
    name: '3x3x6',
    width: 36,
    length: 36,
    height: 72,
    description: 'Place a tent to start your grow.',
    amazonProducts: ['recIXXJteSeNdBqUe'],
    recordId: 'rec1TPicHsGshFRvw',
    linkedASINs: [],
  },
  {
    name: '2x2x2',
    width: 24,
    length: 24,
    height: 24,
    description: 'Place a tent to start your grow.',
    amazonProducts: ['recMyip99OvuWMxow'],
    recordId: 'rec4sHMxGdUcMvOz8',
    linkedASINs: [],
  },
  {
    name: '3x1.5x5.25',
    width: 18,
    length: 36,
    height: 63,
    description: 'Place a tent to start your grow.',
    amazonProducts: ['recVtznduaRQEgQXr'],
    recordId: 'rec4umbhmj1wzDlFp',
    linkedASINs: [],
  },
  {
    name: '8x4x6',
    width: 48,
    length: 96,
    height: 72,
    description: 'Place a tent to start your grow.',
    amazonProducts: ['reczkk5mjVOlXtlJg'],
    recordId: 'rec79yuAePfnI53VQ',
    linkedASINs: [],
  },
  {
    name: '4x4x6.5',
    width: 48,
    length: 48,
    height: 78,
    description: 'Place a tent to start your grow.',
    amazonProducts: ['reczkk5mjVOlXtlJg'],
    recordId: 'recQyqFwjJ3AMrMy6',
    linkedASINs: [],
  },
  {
    name: '2x2x4',
    width: 24,
    length: 24,
    height: 48,
    description: 'Place a tent to start your grow.',
    amazonProducts: ['rec8HP8bLNKUQ1hUo'],
    recordId: 'recWoV5L9gVgEp5Lf',
    linkedASINs: [],
  },
  {
    name: '5x5x6.5',
    width: 60,
    length: 60,
    height: 78,
    description: 'Place a tent to start your grow.',
    amazonProducts: ['recLLpu2TvPZceNOy'],
    recordId: 'recXjEqOQ44ehArU0',
    linkedASINs: [],
  },
  {
    name: '2.5x2.5x5.25',
    width: 30,
    length: 30,
    height: 63,
    description: 'Place a tent to start your grow.',
    amazonProducts: ['rec5lKUAKiYTv6tWW'],
    recordId: 'recZ6WC1YY2oLaXiQ',
    linkedASINs: [],
  },
  {
    name: '4x2x5',
    width: 24,
    length: 48,
    height: 60,
    description: 'Place a tent to start your grow.',
    amazonProducts: ['rec9zmiLx6DvXFq9H'],
    recordId: 'recfd6mugALYpWz3I',
    linkedASINs: [],
  },
  {
    name: '8x4x6.5',
    width: 48,
    length: 96,
    height: 78,
    description: 'Place a tent to start your grow.',
    amazonProducts: ['rec9zmiLx6DvXFq9H'],
    recordId: 'recjT7GSgImOmLtJU',
    linkedASINs: [],
  },
  {
    name: '5x2.5x6.5',
    width: 30,
    length: 60,
    height: 78,
    description: 'Place a tent to start your grow.',
    amazonProducts: ['recX3Z8xjntEWpu8a'],
    recordId: 'reckaSDfKxconktv1',
    linkedASINs: [],
  },
];

export default airtableTents;
