import { createSlice } from '@reduxjs/toolkit';

import planReduxAdapter from './playgourndPlanReduxAdapter';

export const playgroundPlanSlice = createSlice({
  name: 'playgroundPlan',
  initialState: planReduxAdapter.getInitialState(),
  reducers: {
    create: planReduxAdapter.addOne,
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: (builder) => {
    // builder
      // .addCase(incrementAsync.pending, (state) => {
      //   state.status = 'loading';
      // })
      // .addCase(incrementAsync.fulfilled, (state, action) => {
      //   state.status = 'idle';
      //   state.value += action.payload;
      // });
  // },
});

export const { create } = playgroundPlanSlice.actions;

export default playgroundPlanSlice.reducer;
