const airtablePots = [
  {
    name: '1 Gallon',
    width: 6,
    length: 6,
    height: 7.9,
    description: 'Up to 6" plant height',
    ASIN: 'B08HRVR5TV',
  },
  {
    name: '2 Gallon',
    width: 9,
    length: 9,
    height: 7.9,
    description: 'Up to 12" plant height',
    ASIN: 'B08HRS2TDC',
  },
  {
    name: '3 Gallon',
    width: 9,
    length: 9,
    height: 9.9,
    description: 'Up to 18" plant height',
    ASIN: 'B08HRR1ZJM',
  },
  {
    name: '5 Gallon',
    width: 12,
    length: 12,
    height: 9.9,
    description: 'Up to 30" plant height',
    ASIN: 'B00TF9E6XE',
  },
  {
    name: '7 Gallon',
    width: 15,
    length: 15,
    height: 9.9,
    description: 'Up to 42" plant height',
    ASIN: 'B08HRVMPX9',
  },
  {
    name: '10 Gallon',
    width: 15,
    length: 15,
    height: 11.9,
    description: 'Up to 60" plant height',
    ASIN: 'B00VWU30PO',
  },
  {
    name: '15 Gallon',
    width: 21,
    length: 21,
    height: 11.9,
    description: 'Up to 90" plant height',
    ASIN: 'B00VWU37QG',
  },
  {
    name: '20 Gallon',
    width: 21,
    length: 21,
    height: 15.9,
    description: 'Up to 120" plant height',
    ASIN: 'B097PJW1QP',
  },
  {
    name: '25 Gallon',
    width: 21,
    length: 21,
    height: 15.9,
    description: 'Up to 150" plant height',
    ASIN: 'B097PHG8PV',
  },
  {
    name: '30 Gallon',
    width: 24,
    length: 24,
    height: 15.9,
    description: 'For multiple plants',
    ASIN: 'B097PJS964',
  },
  {
    name: '50 Gallon',
    width: 30,
    length: 30,
    height: 19.1,
    description: 'For multiple plants',
    ASIN: 'B07SVYP3V5',
  },
  {
    name: '100 Gallon',
    width: 39,
    length: 39,
    height: 19.9,
    description: 'For multiple plants',
    ASIN: 'B07SQQQPYY',
  },
];

export default airtablePots;
