import { PotRecord } from '../../src/airtable/pots';

const airtablePots: PotRecord[] = [
  {
    name: '1 Gallon',
    width: 6,
    length: 6,
    height: 7.9,
    description: 'Up to 6" plant height',
    amazonProductASINs: ['recbCJpZr8TbCS5S6'],
    recordId: 'recTe3Bcz4mhqgQqN',
  },
  {
    name: '2 Gallon',
    width: 9,
    length: 9,
    height: 7.9,
    description: 'Up to 12" plant height',
    amazonProductASINs: ['recj7vL54wZUsMh0Y'],
    recordId: 'recWkZUqlHT1MQlmY',
  },
  {
    name: '3 Gallon',
    width: 9,
    length: 9,
    height: 9.9,
    description: 'Up to 18" plant height',
    amazonProductASINs: ['recgOXQCD44T4P6vC'],
    recordId: 'recpXtK8fdcyxpnxS',
  },
  {
    name: '5 Gallon',
    width: 12,
    length: 12,
    height: 9.9,
    description: 'Up to 30" plant height',
    amazonProductASINs: ['recuTHEUoRKSE1dMe'],
    recordId: 'rectoPyGtsFtEPdsq',
  },
  {
    name: '7 Gallon',
    width: 15,
    length: 15,
    height: 9.9,
    description: 'Up to 42" plant height',
    amazonProductASINs: ['recofj5jNIFF4DIQp'],
    recordId: 'recc5Q1cf0W9XcmjA',
  },
  {
    name: '10 Gallon',
    width: 15,
    length: 15,
    height: 11.9,
    description: 'Up to 60" plant height',
    amazonProductASINs: ['recR0RCgGhHQ5UnEG'],
    recordId: 'recCxLaIt2v41uXCi',
  },
  {
    name: '15 Gallon',
    width: 21,
    length: 21,
    height: 11.9,
    description: 'Up to 90" plant height',
    amazonProductASINs: ['recI7XgdRexF6EU8y'],
    recordId: 'rec5Ke5yanmuoF0m0',
  },
  {
    name: '20 Gallon',
    width: 21,
    length: 21,
    height: 15.9,
    description: 'Up to 120" plant height',
    amazonProductASINs: ['recfV70miedJp9bf0'],
    recordId: 'recqx30FEvLQUgzzO',
  },
  {
    name: '25 Gallon',
    width: 21,
    length: 21,
    height: 15.9,
    description: 'Up to 150" plant height',
    amazonProductASINs: ['recdyHhOgP0Tnb8fF'],
    recordId: 'rec8ZyS7LbXLwXBss',
  },
  {
    name: '30 Gallon',
    width: 24,
    length: 24,
    height: 15.9,
    description: 'For multiple plants',
    amazonProductASINs: ['recUJ72nHihEQa7IS'],
    recordId: 'recVCGQDNiJ6GQK0J',
  },
  {
    name: '50 Gallon',
    width: 30,
    length: 30,
    height: 19.1,
    description: 'For multiple plants',
    amazonProductASINs: ['rec9CjHOb3hpPUK8X'],
    recordId: 'recpzNPTyUT6dT8Hp',
  },
  {
    name: '100 Gallon',
    width: 39,
    length: 39,
    height: 19.9,
    description: 'For multiple plants',
    amazonProductASINs: ['recIyjjlN9f7JHRkF'],
    recordId: 'rec2YeERza71U3WZV',
  },
];

export default airtablePots;
