name: Development Workflow
on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "15.14.0"
      - run: npm ci

  build:
    runs-on: ubuntu-18.04
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "15.14.0"
      - run: npm ci

      - run: npm run build --if-present

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  test:
    runs-on: ubuntu-18.04
    needs: setup
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "15.14.0"
      - run: npm ci

      - run: npm test

  deploy:
    runs-on: ubuntu-18.04
    needs:
      - build
      - test
    steps:
      - uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Deploy to development environment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "zuut-dev" #Must be unique in Heroku
          heroku_email: "zuutheroku@gmail.com"
          #healthcheck: true // save for later
          #delay: 30 // saving for healthcheck if we want it later, set to 30 secs
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        #timeout-minutes: 2
