name: dev
on:
  push:
    branches:
      - main
jobs:
  ui_unit_test:
    runs-on: ubuntu-18.04
    env:
      CI: 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15.14.0'
          cache: 'npm'
      - run: npm ci
        working-directory: ./ui

      - name: Run unit tests
        run: npm test -- --reporters=default --reporters=jest-junit
        working-directory: ./ui

  browser_tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: browser-tests
        uses: actions/setup-node@v2
        with:
          node-version: '15.14.0'
          cache: 'npm'
      - run: npm ci
      - run: cd e2e && npm ci && npx cypress verify
      - run: docker compose build
      - run: docker compose up -d
      - run: npm run e2e
        env:
          CYPRESS_AUTH_USERNAME: ${{ secrets.CYPRESS_AUTH_USERNAME }}
          CYPRESS_AUTH_PASSWORD: ${{ secrets.CYPRESS_AUTH_PASSWORD }}

  backend_unit_test:
    runs-on: ubuntu-18.04
    env:
      CI: 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15.14.0'
          cache: 'npm'
      - run: npm ci
        working-directory: ./backend

      - name: Run unit tests
        run: npm test -- --reporters=default --reporters=jest-junit
        working-directory: ./backend

  deploy:
    runs-on: ubuntu-18.04
    needs:
      - ui_unit_test
      - browser_tests
      - backend_unit_test
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to development environment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'zuut-dev' #Must be unique in Heroku
          heroku_email: 'zuutheroku@gmail.com'
          #healthcheck: true // save for later
          #delay: 30 // saving for healthcheck if we want it later, set to 30 secs
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          REACT_APP_MIXPANEL_TOKEN: 'e5d2699a9fe25e45c53c85472e799725'
        #timeout-minutes: 2
