name: dev
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to development environment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'zuut-dev' #Must be unique in Heroku
          heroku_email: 'zuutheroku@gmail.com'
          usedocker: true
          #healthcheck: true // save for later
          #delay: 30 // saving for healthcheck if we want it later, set to 30 secs
          docker_build_args: |
            MIXPANEL_TOKEN
        env:
          MIXPANEL_TOKEN: '8e6a75065b59fcc16af32951e8340a92'
        #timeout-minutes: 2
