name: dev
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false

  ui_unit_test:
    runs-on: ubuntu-18.04
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "15.14.0"
          cache: "npm"
      - run: npm ci
        working-directory: ./ui

      - name: Run unit tests
        run: npm test -- --reporters=default --reporters=jest-junit
        working-directory: ./ui

  ui_browser_tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: browser-tests
        uses: actions/setup-node@v2
        with:
          node-version: "15.14.0"
          cache: "npm"
      - run: npm ci
        working-directory: ./ui
      - run: npm run dev:noauth &
        working-directory: ./ui
      - run: npm run taiko-test
        working-directory: ./ui

  backend_unit_test:
    runs-on: ubuntu-18.04
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "15.14.0"
          cache: "npm"
      - run: npm ci
        working-directory: ./backend

      - name: Run unit tests
        run: npm test -- --reporters=default --reporters=jest-junit
        working-directory: ./backend

  deploy:
    runs-on: ubuntu-18.04
    needs:
      - build
      - ui_unit_test
      - ui_browser_tests
      - backend_unit_test
    steps:
      - uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Deploy to development environment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "zuut-dev" #Must be unique in Heroku
          heroku_email: "zuutheroku@gmail.com"
          #healthcheck: true // save for later
          #delay: 30 // saving for healthcheck if we want it later, set to 30 secs
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        #timeout-minutes: 2
