name: prod
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heorku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "zuut-prod" #Must be unique in Heroku
          heroku_email: "zuutheroku@gmail.com"
          #healthcheck: true // save for later
          #delay: 30 // saving for healthcheck if we want it later, set to 30 secs
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        #timeout-minutes: 2
