name: prod
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heorku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'zuut-prod' #Must be unique in Heroku
          heroku_email: 'zuutheroku@gmail.com'
          usedocker: true
          #healthcheck: true // save for later
          #delay: 30 // saving for healthcheck if we want it later, set to 30 secs
          docker_build_args: |
            MIXPANEL_TOKEN
        env:
          MIXPANEL_TOKEN: 'c3c6fa03d2d58bf1cb9fe4a7a211ba79'
        #timeout-minutes: 2
